name: presensi_polsri
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cloud_firestore: 4.8.4
  convex_bottom_bar: 3.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: 4.7.2
  firebase_core: ^2.15.0
  firebase_storage: 11.2.5
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: 4.6.5
  image_picker: ^1.0.2
  intl: 0.18.1
  open_file: ^3.2.1
  path_provider: ^2.0.11
  pdf: ^3.3.0
  qr_flutter: ^4.0.0
  syncfusion_flutter_datepicker: ^22.2.8

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_lints: 2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
