// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXsXvaqFvvBNKe9sSQaUseO7vSajQGtaI',
    appId: '1:384598659619:web:802174fc73edca36315796',
    messagingSenderId: '384598659619',
    projectId: 'presence-qrcode12',
    authDomain: 'presence-qrcode12.firebaseapp.com',
    storageBucket: 'presence-qrcode12.appspot.com',
    measurementId: 'G-HJ2GE7B2NJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCs-YcfZwpyKjLgIP54WjsoXqlis4bosY',
    appId: '1:384598659619:android:de47b2c0a7e3f174315796',
    messagingSenderId: '384598659619',
    projectId: 'presence-qrcode12',
    storageBucket: 'presence-qrcode12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8PTOdpOtsUVX4KZqIEEuLqsfq9GCXjTY',
    appId: '1:384598659619:ios:898a479f398a8b6a315796',
    messagingSenderId: '384598659619',
    projectId: 'presence-qrcode12',
    storageBucket: 'presence-qrcode12.appspot.com',
    iosClientId: '384598659619-ahjj2nno59u66v6vg38fdv5frs3ov9v0.apps.googleusercontent.com',
    iosBundleId: 'com.ekteknikkomputer.presensiPolsri',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8PTOdpOtsUVX4KZqIEEuLqsfq9GCXjTY',
    appId: '1:384598659619:ios:898a479f398a8b6a315796',
    messagingSenderId: '384598659619',
    projectId: 'presence-qrcode12',
    storageBucket: 'presence-qrcode12.appspot.com',
    iosClientId: '384598659619-ahjj2nno59u66v6vg38fdv5frs3ov9v0.apps.googleusercontent.com',
    iosBundleId: 'com.ekteknikkomputer.presensiPolsri',
  );
}
